### ISSUE TITLE
LazyBuilder_Taxonomy::remove() の実装変更

### ISSUE THREAD

**Issue by e-g-kangaroo** [e-g-kangaroo/lazybuilder#25]
dry run で変更点を表示する時、現状の実装ではいくつかの問題点がある。
1. すでの削除済みのtermや、未登録のtermには get_term_by() が使用できない。
    - wp_delete_term()はterm_idでしか削除ができないので、slugで削除しようとした場合、get_term_by()でterm_idを取得する必要がある。
2. 1 の場合更に、term_idを指定して削除しようした際に、削除しようとしたtaxonomyのslugなどの情報を引き出せない。

上記の問題を解決する実装を再設計する。

**Comment by niaeashes** [comment]
そもそも remove() の場合は slug のみの表示でいいんじゃない？

**Comment by niaeashes** [comment]
うん、やっぱ LazyBuilder_Listener が完全な情報を取得しようとしてるところに問題があると思う。

remove() の foreach の先頭で

``` php
$listener = LazyBuilder_Listener::instance();
$listener->notify('remove', 'Taxonomy', array_merge(array('taxonomy' => $taxonomy)), array('identify' => $term_identify));
```

ってして、$term_identify の内容がなんであれ「こういうやつを削除したいんだよ」っていう表示だけで良いと思う。
（強いて言うなら、up 内部にタクソノミーの定義がある場合はそれを流用するとか？）
