### ISSUE TITLE
LazyBuilder_Listener が dry-run フラグを持ってるので、LazyBuilder に移す

### ISSUE THREAD

**Issue by niaeashes** [e-g-kangaroo/lazybuilder#26]
`LazyBuilder_Listener` の役割は「実行内容を聞き取ること」であって、「どのような実行形式か」というプロセスの情報を持つべきじゃない、と思う。

**Comment by niaeashes** [comment]
よく見たら LazyBuilder_Listener がプロパティで保持してるだけか。

**Comment by e-g-kangaroo** [comment]
静的に読み込めるように書き換えます。
