### ISSUE TITLE
そもそも Current builder を表示する意味って……？

### ISSUE THREAD

**Issue by niaeashes** [e-g-kangaroo/lazybuilder#31]
素朴な疑問なんだけど、Current って「そのビルダまでは実行が終わってる」ってことだよね？

というのも、初期状態では「何も実行していない」わけだから、当然現在位置は 0 なので、1個目のビルダを実行すると1になるのが自然で、Current は「実行が終わったビルダのうち、一番番号が大きいやつ」と一致することになるはず。

だとすると、ビューに出したいのって Current + 1 のビルダなんじゃなかろうか。つまり、Next Builder。（だって、既に実行してるのはどうでもよくて、次 UP を押すとどうなる？ ってのが知りたいはず）

と思ったんだけど、そこんとこどうでしょう e-g-kangaroo 先生。

**Comment by e-g-kangaroo** [comment]
そうですね！
じゃあ、Nextに変更します。

**Comment by niaeashes** [comment]
Refs #33
